services:
  mkdocs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "mkdocs"
    volumes:
      - "./docs:/docs"
      - "./mkdocs.yml:/mkdocs.yml"
    env_file:
      - .env

    ports:
      - "80:8000"
      
    restart: unless-stopped