services:
  mkdocs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "mkdocs"
    volumes:
      - "./docs:/docs"
      - "./mkdocs.yml:/mkdocs.yml"
    environment:
      - GITHUB_TOKEN=$(GITHUB_TOKEN)

    ports:
      - "80:8000"
      
    restart: unless-stopped