services:
  mkdocs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "mkdocs"
    volumes:
      - "./docs:/docs"
      - "./mkdocs.yml:/mkdocs.yml"
      - "./config:/root/.ssh/config"
      - "./id_ed25519:/root/.ssh/id_ed25519"

    ports:
      - "80:8000"